#!/usr/bin/env babel-node

import {getApplication} from '../../lib/stormpath'

getApplication()
  .then(app => {
    app.sendPasswordResetEmail({ email: process.argv[2] }, (err, passwordReset) => {
      if (err) {
        console.error(err)
        console.error(err.stack)
        process.exit(1)
      } else {
        console.log(`Password Reset: ${JSON.stringify(passwordReset, null, '\t')}`)
        process.exit(0)
      }
    })
  })
  .catch(err => {
    console.error(err)
    console.error(err.stack)
    process.exit(1)
  })
